<?php

return array(
    '01-01-and-if-sunday-then-next-tuesday' => '= 01-01 and if sunday then next tuesday',
    '01-02-and-if-sunday-then-next-monday'  => '= 01-02 substitute',
    '03-02'                                 => '03-02',
    '03-07'                                 => '03-07',
    '03-08'                                 => '03-08',
    '03-14-and-if-sunday-then-next-monday'  => '= 03-14 substitute',
    '03-22-and-if-sunday-then-next-monday'  => '= 03-22 substitute',
    '04-01'                                 => '04-01',
    'easter'                                => '= easter',
    'easter-1'                              => '= easter 1',
    'orthodox'                              => '= orthodox',
    'orthodox-1'                            => '= orthodox 1',
    '05-01-and-if-sunday-then-next-monday'  => '= 05-01 substitute',
    '06-01'                                 => '06-01',
    '10-19-and-if-sunday-then-next-monday'  => '= 10-19 substitute',
    '11-22'                                 => '11-22',
    '11-28-and-if-sunday-then-next-monday'  => '= 11-28 substitute',
    '11-29-and-if-sunday-then-next-monday'  => '= 11-29 substitute',
    '12-08-and-if-sunday-then-next-monday'  => '= 12-08 substitute',
    '12-25-and-if-sunday-then-next-monday'  => '= 12-25 substitute',
    '1-shawwal'                             => '= 1 Shawwal',
    '10-dhu-al-hijjah'                      => '= 10 Dhu al-Hijjah',
);
