<?php

return array(
    'new-year'                                           => '01-01',
    'easter-48'                                          => '= easter -48',
    'easter-47'                                          => '= easter -47',
    '03-24'                                              => '03-24',
    'substitutes-03-24'                                  => '= 03-24 if Tuesday then previous Monday and if Thursday then next Friday',
    'easter-3'                                           => '= easter -3',
    'easter-2'                                           => '= easter -2',
    'day-of-the-veterans-and-the-fallen-of-malvinas-war' => '04-02',
    'substitutes-04-02'                                  => '= 04-02 if Tuesday then previous Monday and if Thursday then next Friday',
    '05-01'                                              => '05-01',
    'substitutes-05-01'                                  => '= 05-01 if Tuesday then previous Monday and if Thursday then next Friday',
    '05-25'                                              => '05-25',
    'substitutes-05-25'                                  => '= 05-25 if Tuesday then previous Monday and if Thursday then next Friday',
    '06-20'                                              => '06-20',
    'substitutes-06-20'                                  => '= 06-20 if Tuesday then previous Monday and if Thursday then next Friday',
    '07-09'                                              => '07-09',
    '3rd-monday-of-august'                               => '= third Monday of August',
    '10-12'                                              => '= 10-12 if Tuesday,Wednesday then previous Monday and if Thursday,Friday,Saturday,Sunday then next Monday',
    '4th-monday-of-november'                             => '= fourth Monday of November',
    '12-08'                                              => '12-08',
    'substitutes-12-08'                                  => '= 12-08 if Tuesday then previous Monday and if Thursday then next Friday',
    'substitutes-12-24'                                  => '= 12-24 if Tuesday then previous Monday',
    'christmas'                                          => '12-25',
    'substitutes-12-25'                                  => '= 12-25 if Thursday then next Friday',
);
