<?php

return array(
    '05-21-and-if-sunday-then-next-tuesday' => '= 05-21 if sunday then next tuesday',
    '05-22-and-if-sunday-then-next-monday'  => '= 05-22 substitute',
    '07-13-and-if-sunday-then-next-tuesday' => '= 07-13 if sunday then next tuesday',
    '07-14-and-if-sunday-then-next-monday'  => '= 07-14 substitute',
    '01-01-and-if-sunday-then-next-tuesday' => '= 01-01 if sunday then next tuesday',
    '01-02-and-if-sunday-then-next-monday'  => '= 01-02 substitute',
    '05-01-and-if-sunday-then-next-tuesday' => '= 05-01 if sunday then next tuesday',
    '05-02-and-if-sunday-then-next-monday'  => '= 05-02 substitute',
    'orthodox-2'                            => '= orthodox -2',
    'orthodox'                              => '= orthodox',
    '12-24'                                 => '12-24',
    'christmas'                             => '12-25',
    'christmas-next-day'                    => '12-26',
    'easter-2'                              => '= easter -2',
    'easter'                                => '= easter',
    'easter-1'                              => '= easter 1',
    '11-01'                                 => '11-01',
    'julian-12-24'                          => '= julian 12-24',
    'julian-12-25'                          => '= julian 12-25',
    'julian-12-26'                          => '= julian 12-26',
    //    '1-shawwal-p3d'                         => '= 1 Shawwal P3D',
    //    '10-dhu-al-hijjah-p3d'                  => '= 10 Dhu al-Hijjah P3D',
    //    '1-muharram'                            => '= 1 Muharram',
    //    '12-rabi-al-awwal'                      => '= 12 Rabi al-awwal',
    //    '27-rajab'                              => '= 27 Rajab',
    //    '15-shaban'                             => '= 15 Shaban',
    //    '1-ramadan'                             => '= 1 Ramadan',
    //    '27-ramadan'                            => '= 27 Ramadan',
    //    '15-nisan-p2d'                          => '= 15 Nisan P2D',
    //    '1-tishrei'                             => '= 1 Tishrei',
    //    '10-tishrei-p2d'                        => '= 10 Tishrei P2D',
);
