<?php

return array(
    '01-01-and-if-sunday-then-next-monday'        => '= 01-01 substitute',
    'orthodox'                                    => '= orthodox',
    'orthodox-1'                                  => '= orthodox 1',
    '05-01-and-if-sunday-then-next-monday'        => '= 05-01 substitute',
    '05-24-and-if-sunday-then-next-monday'        => '= 05-24 substitute',
    '08-02-and-if-sunday-then-next-monday'        => '= 08-02 substitute',
    '09-08-and-if-sunday-then-next-monday'        => '= 09-08 substitute',
    '10-11-and-if-sunday-then-next-monday'        => '= 10-11 substitute',
    '10-23-and-if-sunday-then-next-monday'        => '= 10-23 substitute',
    '12-08-and-if-sunday-then-next-monday'        => '= 12-08 substitute',
    'orthodox-2'                                  => '= orthodox -2',
    'orthodox-47'                                 => '= orthodox 47',
    'orthodox-49'                                 => '= orthodox 49',
    'easter-1'                                    => '= easter 1',
    'christmas'                                   => '12-25',
    'julian-12-25-and-if-sunday-then-next-monday' => '= julian 12-25 substitute',
    'julian-12-24'                                => '= julian 12-24',
    'julian-01-06'                                => '= julian 01-06',
    'julian-08-15'                                => '= julian 08-15',
    '1-shawwal-and-if-sunday-then-next-monday'    => '= 1 Shawwal substitute',
    '10-dhu-al-hijjah'                            => '= 10 Dhu al-Hijjah',
    '10-tishrei'                                  => '= 10 Tishrei',
);
