<?php

return [
    'new-year'                => '01-01',
    '2nd-sunday-of-february'  => '= second Sunday of February',
    'easter-49'               => '= easter 49',
    'easter-7'                => '= easter -7',
    'easter-3'                => '= easter -3',
    'easter-2'                => '= easter -2',
    'easter-p1'               => '= easter 1',
    'easter'                  => '= easter',
    '05-01'                   => '05-01',
    '05-08'                   => '05-08',
    '05-17'                   => '05-17',
    'easter-39'               => '= easter 39',
    'easter-50'               => '= easter 50',
    '06-23'                   => '06-23',
    '2nd-sunday-of-november'  => '= second Sunday of November',
    '4th-sunday-before-12-24' => '= Sunday before 12-03',
    '3rd-sunday-before-12-24' => '= Sunday before 12-10',
    '2nd-sunday-before-12-24' => '= Sunday before 12-17',
    '1st-sunday-before-12-24' => '= Sunday before 12-24',
    'christmas'               => '12-25',
    'christmas-next-day'      => '12-26',
];
