<?php

return array(
    'martyrs-day'                                   => 'Qara Yanvar',
    'spring-festival'                               => 'Novruz',
    'day-of-victory-over-fascism'                   => 'Faşizm üzərində qələbə günü',
    'republic-day'                                  => 'Respublika günü',
    'national-salvation-day'                        => 'Azərbaycan xalqının Milli Qurtuluş günü',
    'azerbaijan-armed-forces-day'                   => 'Azərbaycan Respublikasının Silahlı Qüvvələri günü',
    'independence-day'                              => 'Dövlət Müstəqilliyi günü',
    'flag-day'                                      => 'Dövlət Bayrağı günü',
    'constitution-day'                              => 'Konstitusiya günü',
    'national-revival-day'                          => 'Milli Dirçəliş günü',
    'international-solidarity-day-of-azerbaijanis'  => 'Dünya azərbaycanlıların həmrəyliyi günü',
    '01-20'                                         => 'Qara Yanvar',
    '03-20'                                         => 'Novruz',
    '05-09'                                         => 'Faşizm üzərində qələbə günü',
    '05-28'                                         => 'Respublika günü',
    '06-15'                                         => 'Azərbaycan xalqının Milli Qurtuluş günü',
    '06-26'                                         => 'Azərbaycan Respublikasının Silahlı Qüvvələri günü',
    '10-18'                                         => 'Dövlət Müstəqilliyi günü',
    '11-09'                                         => 'Dövlət Bayrağı günü',
    '11-12'                                         => 'Konstitusiya günü',
    '11-17'                                         => 'Milli Dirçəliş günü',
    '12-31'                                         => 'Dünya azərbaycanlıların həmrəyliyi günü',
    'new-year'                                      => 'Yeni il',
    '03-08'                                         => 'Qadınlar günü',
    '1-shawwal'                                     => 'Ramazan Bayramı',
    '10-dhu-al-hijjah'                              => 'Qurban Bayramı',
    'substitutes'                                   => 'əvəz gün',
    '05-09-and-if-saturday,sunday-then-next-monday' => 'Faşizm üzərində qələbə günü',
    '05-28-and-if-saturday,sunday-then-next-monday' => 'Respublika günü',
    '06-15-and-if-saturday,sunday-then-next-monday' => 'Azərbaycan xalqının Milli Qurtuluş günü',
    '06-26-and-if-saturday,sunday-then-next-monday' => 'Azərbaycan Respublikasının Silahlı Qüvvələri günü',
    '10-18-and-if-saturday,sunday-then-next-monday' => 'Dövlət Müstəqilliyi günü',
    '11-09-and-if-saturday,sunday-then-next-monday' => 'Dövlət Bayrağı günü',
    '12-31-and-if-saturday,sunday-then-next-monday' => 'Dünya azərbaycanlıların həmrəyliyi günü',
);
