<?php

return [
    'substitutes'                          => 'zamjena dan',
    '01-02-and-if-sunday-then-next-monday' => 'Drugi dan Nove Godine',
    '05-02-and-if-sunday-then-next-monday' => 'Drugi dan Dana rada',
    '11-25'                                => 'Dan državnosti',
    '01-09'                                => 'Dan Republike',
    '05-09'                                => 'Dan pobjede',
    '11-21'                                => 'Dan uspostave Opšteg okvirnog sporazuma za mir u Bosni i Hercegovini',
    'new-year'                             => 'Novogodisnji dan',
    '05-01'                                => 'Radni dan',
    '11-01'                                => 'Dita e të gjithë Shenjtorëve',
    '12-24'                                => 'Badnji dan',
    'christmas'                            => 'Božić',
    'easter-2'                             => 'Dobar petak',
    'easter'                               => 'Vaskrs',
    'easter-1'                             => 'Uskrsni ponedjeljak',
    'julian-01-01'                         => 'Pravoslavni novogodišnji dan',
    'julian-12-25'                         => 'Pravoslavni Božić',
    'orthodox'                             => 'Pravoslavni Vaskrs',
    '1-muharram'                           => 'Nova hidžretska godina',
    '12-rabi-al-awwal'                     => 'Mevlud',
    '27-rajab'                             => 'Lejletul Mi\'radž',
    '15-shaban'                            => 'Lejletul berat',
    '1-ramadan'                            => 'Prvi dan posta',
    '27-ramadan'                           => 'Lejletul kadr',
    '1-shawwal'                            => 'Ramazanski bajram',
    '10-dhu-al-hijjah'                     => 'Kurbanski bajram',
    '15-nisan'                             => 'Pesah',
    '1-tishrei'                            => 'Roš Hašana',
    '10-tishrei'                           => 'Jom Kipur',
    'independence-day'                     => 'Dan nezavisnosti',
];
