<?php

return [
    'new-year'                               => 'Nový rok; Den obnovy samostatného českého státu',
    'ugly-wednesday'                         => 'Škaredá středa',
    'liberation-day'                         => 'Den vítězství or Den osvobození',
    'saints-cyril-and-methodius-day'         => 'Den slovanských věrozvěstů Cyrila a Metoděje',
    'jan-hus-day'                            => 'Den upálení mistra Jana Husa',
    'st.-wenceslas-day'                      => 'Den české státnosti',
    'independent-czechoslovak-state-day'     => 'Den vzniku samostatného československého státu',
    'struggle-for-freedom-and-democracy-day' => 'Den boje za svobodu a demokracii',
    'easter-4'                               => 'Škaredá středa',
    '05-08'                                  => 'Den vítězství or Den osvobození',
    '07-05'                                  => 'Den slovanských věrozvěstů Cyrila a Metoděje',
    '07-06'                                  => 'Den upálení mistra Jana Husa',
    '09-28'                                  => 'Den české státnosti',
    '10-28'                                  => 'Den vzniku samostatného československého státu',
    '11-17'                                  => 'Den boje za svobodu a demokracii',
    '05-01'                                  => 'Svátek práce',
    '12-24'                                  => 'Štědrý den',
    'christmas'                              => '1. svátek vánoční',
    'christmas-next-day'                     => '2. svátek vánoční',
    'easter-3'                               => 'Zelený čtvrtek',
    'easter-2'                               => 'Velikonoční pátek',
    'easter-1'                               => 'Bílá sobota',
    'easter'                                 => 'Neděle velikonoční',
    'mothers-day'                            => 'Den matek',
];
