<?php

return array(
    'easter-48'                        => 'Fastelavn',
    'prayer-day'                       => 'Store Bededag',
    'flag-day'                         => 'Flagdag',
    'st.olav-s-eve'                    => 'Sankt Olavsaften',
    'st.olav-s-day'                    => 'Sankt Olavs Dag',
    'national-day'                     => 'Nationaldag',
    'easter-26'                        => 'Store Bededag',
    '04-24'                            => 'Flagdag',
    '07-28-12:00-if-sunday-then-00:00' => 'Sankt Olavsaften',
    '07-29'                            => 'Sankt Olavs Dag',
    '06-21'                            => 'Nationaldag',
    'new-year'                         => 'Nytår',
    '01-06'                            => 'Åbenbaring',
    '12-24'                            => 'Juleaften',
    'christmas'                        => '1. Juledag',
    'christmas-next-day'               => '2. Juledag',
    '12-31'                            => 'Nytårsaften',
    'easter-3'                         => 'Skærtorsdag',
    'easter-2'                         => 'Langfredag',
    'easter'                           => 'Påskesøndag',
    'easter-1'                         => 'Anden påskedag',
    'easter-39'                        => 'Kristi Himmelfartsdag',
    'easter-49'                        => 'Pinsedag',
    'easter-50'                        => '2. Pinsedag',
    'constitution-day'                 => 'Grundlovsdag',
    'mothers-day'                      => 'Mors Dag',
);
