<?php

return array(
    'armistice-1918'     => 'Armistice 1918',
    'ascension'          => 'Ascension',
    'assumption'         => 'Assomption',
    'christmas'          => 'Christmas',
    'christmas-next-day' => 'Christmas next day',
    'easter'             => 'Easter',
    'easter-monday'      => 'Easter Monday',
    'epiphany'           => 'Epiphany',
    'good-friday'        => 'Good Friday',
    'independence-day'   => 'Independence Day',
    'labor-day'          => 'Labor Day',
    'liberation-day'     => 'Liberation Day',
    'memorial-day'       => 'Memorial Day',
    'mlk-day'            => 'Martin Luther King Jr. Day',
    'national-day'       => 'National Day',
    'new-year'           => 'New Year',
    'new-year-next-day'  => 'New Year next day',
    'pentecost'          => 'Pentecost',
    'pentecost-monday'   => 'Pentecost Monday',
    'preseren-day'       => 'Prešeren Day',
    'rebellion-day'      => 'Rebellion Day',
    'reformation-day'    => 'Reformation Day',
    'royal-day'          => 'Royal Day',
    'thanksgiving'       => 'Thanksgiving',
    'toussaint'          => 'Toussaint',
    'vacation-day'       => 'Vacation Day',
    'vacation-next-day'  => 'Vacation Day next day',
    'victory-1945'       => 'Victory 1945',
);
