<?php

return [
    'anniversary-of-the-tartu-peace-treaty'                           => 'Tartu rahulepingu aastapäev',
    'native-language-day'                                             => 'emakeelepäev',
    'national-flag-day'                                               => 'Eesti lipu päev',
    'day-of-mourning-and-commemoration'                               => 'leinapäev',
    'victory-day'                                                     => 'võidupüha',
    'midsummer-day'                                                   => 'jaanipäev',
    'day-of-restoration-of-independence'                              => 'taasiseseisvumispäev',
    'european-day-of-remembrance-for-victims-of-stalinism-and-nazism' => 'kommunismi ja natsismi ohvrite mälestuspäev',
    'grandparents-day'                                                => 'vanavanemate päev',
    'resistance-fighting-day'                                         => 'vastupanuvõitluse päev',
    'day-of-declaration-of-sovereignty'                               => 'taassünni päev',
    '02-02'                                                           => 'Tartu rahulepingu aastapäev',
    '03-14'                                                           => 'emakeelepäev',
    '06-04'                                                           => 'Eesti lipu päev',
    '06-14'                                                           => 'leinapäev',
    '06-23'                                                           => 'võidupüha',
    '06-24'                                                           => 'jaanipäev',
    '08-20'                                                           => 'taasiseseisvumispäev',
    '08-23'                                                           => 'kommunismi ja natsismi ohvrite mälestuspäev',
    'second-sunday-of-september'                                      => 'vanavanemate päev',
    '09-22'                                                           => 'vastupanuvõitluse päev',
    '11-16'                                                           => 'taassünni päev',
    'new-year'                                                        => 'uusaasta',
    '01-06'                                                           => 'kolmekuningapäev',
    '05-01'                                                           => 'kevadpüha',
    '11-02'                                                           => 'hingedepäev',
    '12-24'                                                           => 'jõululaupäev',
    'christmas'                                                       => 'esimene jõulupüha',
    'christmas-next-day'                                              => 'teine jõulupüha',
    'easter-2'                                                        => 'suur reede',
    'easter'                                                          => 'lihavõtted',
    'easter-49'                                                       => 'nelipühade 1. püha',
    'fathers-day'                                                     => 'isadepäev',
    'independence-day'                                                => 'iseseisvuspäev',
    'mothers-day'                                                     => 'emadepäev',
    '2nd-sunday-in-september'                                         => 'vanavanemate päev',
];
