<?php

return array(
    'armistice-1918'     => 'Armistice 1918',
    'ascension'          => 'Ascension',
    'assumption'         => 'Assomption',
    'christmas'          => 'Noël',
    'christmas-next-day' => 'Saint Etienne',
    'easter'             => 'Pâques',
    'easter-monday'      => 'Lundi de Pâques',
    'epiphany'           => 'Épiphanie',
    'good-friday'        => 'Vendredi Saint',
    'independence-day'   => 'Indépendance',
    'labor-day'          => 'Fête du travail',
    'liberation-day'     => 'Libération',
    'memorial-day'       => 'Jour commémoratif',
    'mlk-day'            => 'Jour de Martin Luther King',
    'national-day'       => 'Fête nationale',
    'new-year'           => 'Nouvel an',
    'new-year-next-day'  => 'Lendemain du nouvel an',
    'pentecost'          => 'Pentecôte',
    'pentecost-monday'   => 'Lundi de Pentecôte',
    'preseren-day'       => 'Jour de Prešeren',
    'rebellion-day'      => 'Jour de la Rébellion',
    'reformation-day'    => 'Jour de la Reformation',
    'royal-day'          => 'Jour royal',
    'thanksgiving'       => 'Thanksgiving',
    'toussaint'          => 'Toussaint',
    'vacation-day'       => 'Jour de vacances',
    'vacation-next-day'  => 'Lendemain du jour de vacances',
    'victory-1945'       => 'Victoire 1945',
);
