<?php

return [
    'statehood-day'                         => 'Dan državnosti',
    '06-22'                                 => 'Dan antifašističke borbe',
    '06-25'                                 => 'Dan državnosti',
    '08-05'                                 => 'Dan pobjede i domovinske zahvalnosti',
    '05-07'                                 => 'Sveti Duje',
    '02-03'                                 => 'Sveti Vlaho',
    '07-13-and-if-sunday-then-next-tuesday' => 'Dan državnosti',
    '07-14-and-if-sunday-then-next-monday'  => 'Dan državnosti',
    'new-year'                              => 'Nova godina',
    '01-06'                                 => 'Bogojavljenje, Sveta tri kralja',
    '05-01'                                 => 'Praznik rada',
    '08-15'                                 => 'Velika Gospa',
    '11-01'                                 => 'Svi sveti',
    '11-02'                                 => 'Dušni dan',
    '12-24'                                 => 'Badnji dan',
    'christmas'                             => 'Božić',
    'christmas-next-day'                    => 'Svetog Stjepana',
    'easter-47'                             => 'Pokladni utorak',
    'easter-2'                              => 'Veliki petak',
    'easter'                                => 'Uskrs',
    'easter-1'                              => 'Uskršnji ponedjeljak',
    'easter-60'                             => 'Tijelovo',
    'julian-01-01'                          => 'Pravoslavna Nova Godina',
    'julian-12-25'                          => 'Pravoslavni Božić',
    'orthodox'                              => 'Pravoslavni Uskrs',
    '1-muharram'                            => 'Nova hidžretska godina',
    '1-shawwal'                             => 'Ramazanski bajram',
    '10-dhu-al-hijjah'                      => 'Kurban-bajram',
    '15-nisan'                              => 'Pesač',
    '1-tishrei'                             => 'Roš Hašane',
    '10-tishrei'                            => 'Jom Kipur',
    'independence-day'                      => 'Dan neovisnosti',
    'mothers-day'                           => 'Majčin dan',
    'substitutes'                           => 'zamjena dan',
];
