<?php

return array(
    'memorial-day-of-the-republic'                                => 'A köztársaság emléknapja',
    'memorial-day-for-the-victims-of-the-communist-dictatorships' => 'A kommunista diktatúrák áldozatainak emléknapja',
    'national-day'                                                => 'Nemzeti ünnep',
    'memorial-day-for-the-victims-of-the-holocaust'               => 'A holokauszt áldozatainak emléknapja',
    'national-defense-day'                                        => 'Honvédelmi nap',
    'day-of-national-unity'                                       => 'A nemzeti összetartozás napja',
    'day-of-the-independent-hungary'                              => 'A független Magyarország napja',
    'saint-stephen-s-day'                                         => 'Szent István ünnepe',
    'memorial-day-for-the-martyrs-of-arad'                        => 'Az aradi vértanúk emléknapja',
    'saint-nicholas-day'                                          => 'Mikulás, Télapó',
    '02-01'                                                       => 'A köztársaság emléknapja',
    '02-25'                                                       => 'A kommunista diktatúrák áldozatainak emléknapja',
    '03-15'                                                       => 'Nemzeti ünnep',
    '04-16'                                                       => 'A holokauszt áldozatainak emléknapja',
    '05-21'                                                       => 'Honvédelmi nap',
    '06-04'                                                       => 'A nemzeti összetartozás napja',
    '06-19'                                                       => 'A független Magyarország napja',
    '08-20'                                                       => 'Szent István ünnepe',
    '10-06'                                                       => 'Az aradi vértanúk emléknapja',
    '10-23'                                                       => 'Nemzeti ünnep',
    '12-06'                                                       => 'Mikulás, Télapó',
    'new-year'                                                    => 'Újév',
    '03-08'                                                       => 'Nemzetközi nőnap',
    '05-01'                                                       => 'A munka ünnepe',
    '11-01'                                                       => 'Mindenszentek',
    'christmas'                                                   => 'Karácsony',
    'christmas-next-day'                                          => 'Karácsony másnapja',
    '12-31'                                                       => 'Szilveszter',
    'easter'                                                      => 'Húsvétvasárnap',
    'easter-1'                                                    => 'Húsvéthétfő',
    'easter-49'                                                   => 'Pünkösdvasárnap',
    'easter-50'                                                   => 'Pünkösdhétfő',
    'mothers-day'                                                 => 'Anyák napja',
);
