<?php

return [
    'friday-after-01-18'     => 'Bóndadagur',
    'woman-s-day'            => 'Konudagur',
    'easter-48'              => 'Bolludagur',
    'easter-47'              => 'Sprengidagur',
    'first-day-of-summer'    => 'Sumardagurinn fyrsti',
    'the-seamen-s-day'       => 'Sjómannadagurinn',
    'icelandic-national-day' => 'Íslenski þjóðhátíðardagurinn',
    'commerce-day'           => 'Frídagur verslunarmanna',
    'first-day-of-winter'    => 'Fyrsti vetrardagur',
    'icelandic-language-day' => 'Dagur íslenskrar tungu',
    'st-y�orlyakur-s-day'    => 'Þorláksmessa',
    '02-18'                  => 'Konudagur',
    'thursday-after-04-18'   => 'Sumardagurinn fyrsti',
    'first-sunday-of-june'   => 'Sjómannadagurinn',
    '06-17'                  => 'Íslenski þjóðhátíðardagurinn',
    'monday-of-august'       => 'Frídagur verslunarmanna',
    'saturday-after-10-21'   => 'Fyrsti vetrardagur',
    '11-16'                  => 'Dagur íslenskrar tungu',
    '12-23'                  => 'Þorláksmessa',
    'new-year'               => 'Nýársdagur',
    '01-06'                  => 'Þrettándinn',
    '05-01'                  => 'Hátíðisdagur Verkamanna',
    '12-24'                  => 'Aðfangadagur',
    'christmas'              => 'Jóladagur',
    'christmas-next-day'     => 'Annar í jólum',
    '12-31'                  => 'Gamlársdagur',
    'easter-46'              => 'Öskudagur',
    'easter-7'               => 'Pálmasunnudagur',
    'easter-3'               => 'Skírdagur',
    'easter-2'               => 'Föstudagurinn langi',
    'easter'                 => 'Páskadagur',
    'easter-1'               => 'Annar í páskum',
    'easter-39'              => 'Uppstigningardagur',
    'easter-49'              => 'Hvítasunnudagur',
    'easter-50'              => 'Annar í hvítasunnu',
    'mothers-day'            => 'Mæðradagurinn',
    '1st-sunday-in-june'     => 'Sjómannadagurinn',
    'monday-in-august'       => 'Frídagur verslunarmanna',
];
