<?php

return [
    'korean-new-year'           => '설날',
    'independence-movement-day' => '3·1절',
    'children-s-day'            => '어린이날',
    'buddha-s-birthday'         => '석가탄신일',
    'memorial-day'              => '현충일',
    'liberation-day'            => '광복절',
    'korean-thanksgiving'       => '추석',
    'national-foundation-day'   => '개천절',
    'hangul-day'                => '한글날',
    'korean-01-0-01-p3d'        => '설날',
    '03-01'                     => '3·1절',
    '05-05'                     => '어린이날',
    'korean-4-0-8'              => '석가탄신일',
    '06-06'                     => '현충일',
    '08-15'                     => '광복절',
    'korean-8-0-15-p3d'         => '추석',
    '10-03'                     => '개천절',
    '10-09'                     => '한글날',
    'new-year'                  => '신정',
    'christmas'                 => '기독탄신일',
    'constitution-day'          => '제헌절',
];
