<?php

return array(
    'restoration-of-independence-day'               => 'Latvijas Republikas Neatkarības atjaunošanas diena',
    'midsummer-eve'                                 => 'Līgo Diena',
    'midsummer'                                     => 'Jāņi',
    'republic-day'                                  => 'Latvijas Republikas proklamēšanas diena',
    '05-04'                                         => 'Latvijas Republikas Neatkarības atjaunošanas diena',
    '06-23'                                         => 'Līgo Diena',
    '06-24'                                         => 'Jāņi',
    '11-18'                                         => 'Latvijas Republikas proklamēšanas diena',
    'new-year'                                      => 'Jaunais Gads',
    '05-01'                                         => 'Darba svētki',
    '12-24'                                         => 'Ziemassvētku vakars',
    'christmas'                                     => 'Ziemassvētki',
    'christmas-next-day'                            => 'Otrie Ziemassvētki',
    '12-31'                                         => 'Vecgada vakars',
    'easter-2'                                      => 'Lielā Piektdiena',
    'easter'                                        => 'Lieldienas',
    'easter-1'                                      => 'Otrās Lieldienas',
    'mothers-day'                                   => 'Mātes diena',
    'substitutes'                                   => 'aizstājējs diena',
    '05-04-and-if-saturday,sunday-then-next-monday' => 'Latvijas Republikas Neatkarības atjaunošanas diena',
    '11-18-and-if-saturday,sunday-then-next-monday' => 'Latvijas Republikas proklamēšanas diena',
);
