<?php

return array(
    'saints-cyril-and-methodius-day'               => 'Св. Кирил и Методиј',
    'day-of-the-republic'                          => 'Ден на Републиката',
    'revolution-day'                               => 'Ден на востанието',
    'day-of-the-macedonian-revolutionary-struggle' => 'Ден на македонската револуционерна борба',
    'saint-clement-of-ohrid-day'                   => 'Св. Климент Охридски',
    'friday-before-pentecost'                      => 'петок пред Духовден',
    'day-of-the-albanian-alphabet'                 => 'Ден на Албанската азбука',
    'turkish-language-day'                         => 'Ден на настава на турски јазик',
    'st.-sava'                                     => 'Свети Сава',
    'international-roma-day'                       => 'Меѓународен ден на Ромите',
    'national-day-of-authorities'                  => 'Национален ден на Властите',
    'international-day-of-bosniaks'                => 'Меѓународен ден на Бошњаците',
    '05-24-and-if-sunday-then-next-monday'         => 'Св. Кирил и Методиј',
    '08-02-and-if-sunday-then-next-monday'         => 'Ден на Републиката',
    '10-11-and-if-sunday-then-next-monday'         => 'Ден на востанието',
    '10-23-and-if-sunday-then-next-monday'         => 'Ден на македонската револуционерна борба',
    '12-08-and-if-sunday-then-next-monday'         => 'Св. Климент Охридски',
    'orthodox-47'                                  => 'петок пред Духовден',
    '11-22'                                        => 'Ден на Албанската азбука',
    '12-21'                                        => 'Ден на настава на турски јазик',
    '01-27'                                        => 'Свети Сава',
    '04-08'                                        => 'Меѓународен ден на Ромите',
    '05-23'                                        => 'Национален ден на Властите',
    '09-28'                                        => 'Меѓународен ден на Бошњаците',
);