<?php

return array(
    'armistice-1918'     => 'Wapenstilstand 1918',
    'ascension'          => 'Hemelvaart',
    'assumption'         => 'Veronderstelling',
    'boxing'             => 'Tweede Kerstdag',
    'boyne'              => 'Oranjemensen Dag',
    'christmas'          => 'Eerste Kerstdag',
    'christmas-next-day' => 'Tweede Kerstdag',
    'early-may'          => 'Begin mei feestdag',
    'easter'             => 'Paaszondag',
    'easter-monday'      => 'Paasmaandag',
    'epiphany'           => 'Driekoningen',
    'good-friday'        => 'Goede Vrijdag',
    'independence-day'   => 'Onafhankelijkheidsdag',
    'labor-day'          => 'Dag van de Arbeid',
    'liberation-day'     => 'Bevrijdingsdag',
    'memorial-day'       => 'Herdenkingsdag',
    'mlk-day'            => 'Martin Luther King Jr. Day',
    'national-day'       => 'Nationale Dag',
    'new-year'           => 'Nieuwjaarsdag',
    'new-year-next-day'  => 'Nieuw jaar de volgende dag',
    'pentecost'          => 'Pinksterzondag',
    'pentecost-monday'   => 'Pinkstermaandag',
    'preseren-day'       => 'Prešeren Dag',
    'rebellion-day'      => 'Rebelliedag',
    'reformation-day'    => 'Reformatie Dag',
    'royal-day'          => 'Koningsdag',
    'second-jan'         => 'Nieuw jaar de volgende dag',
    'spring'             => 'Lente feestdag',
    'st-andrews'         => 'St Andrew',
    'st-patricks'        => 'St Patrick',
    'summer'             => 'Summer Bank Holiday',
    'thanksgiving'       => 'Dankzegging',
    'toussaint'          => 'Toussaint',
    'vacation-day'       => 'Vakantiedag',
    'vacation-next-day'  => 'Vakantiedag volgende dag',
    'victory-1945'       => 'Overwinning 1945',
);
