<?php

return array(
    'carnival'                   => 'Fastelavn',
    'constitution-day'           => '17. mai',
    'midsummar-eve'              => 'Sankthansaften',
    'first-sunday-of-advent'     => 'Første søndag i advent',
    'second-sunday-of-advent'    => 'Andre søndag i advent',
    'third-sunday-of-advent'     => 'Tredje søndag i advent',
    'fourth-sunday-of-advent'    => 'Fjerde søndag i advent',
    'easter-49'                  => 'Fastelavn',
    '05-17'                      => '17. mai',
    '06-23'                      => 'Sankthansaften',
    'fourth-sunday-before-12-24' => 'Første søndag i advent',
    'third-sunday-before-12-24'  => 'Andre søndag i advent',
    'second-sunday-before-12-24' => 'Tredje søndag i advent',
    'first-sunday-before-12-24'  => 'Fjerde søndag i advent',
    'new-year'                   => 'Første nyttårsdag',
    '05-01'                      => 'Arbeidernes dag',
    '12-24'                      => 'Julaften',
    'christmas'                  => 'Første Juledag',
    'christmas-next-day'         => 'Andre juledag',
    '12-31'                      => 'Nyttårsaften',
    'easter-7'                   => 'Palmesøndag',
    'easter-3'                   => 'Skjærtorsdag',
    'easter-2'                   => 'Langfredag',
    'easter-1'                   => 'Påskeaften',
    'easter'                     => 'Første påskedag',
    'easter-39'                  => 'Kristi himmelfartsdag',
    'easter-50'                  => 'Andre pinsedag',
    'fathers-day'                => 'Farsdag',
    'liberation-day'             => 'Frigjøringsdagen',
    'mothers-day'                => 'Morsdag',
    '4th-sunday-before-12-24'    => 'Første søndag i advent',
    '3rd-sunday-before-12-24'    => 'Andre søndag i advent',
    '2nd-sunday-before-12-24'    => 'Tredje søndag i advent',
    '1st-sunday-before-12-24'    => 'Fjerde søndag i advent',
);
