<?php

return [
    'betico-croes-day'                                                      => 'Dia di Betico',
    'national-anthem-and-flag-day'                                          => 'Dia di Himno y Bandera',
    'kings-day'                                                             => 'Aña di Rey',
    'dera-gai'                                                              => 'Dera Gai',
    'flag-day'                                                              => 'Dia di Himno i Bandera',
    'curayiao-day'                                                          => 'Pais Kòrsou',
    '01-25'                                                                 => 'Dia di Betico',
    '03-18-and-if-saturday-then-previous-friday-if-sunday-then-next-monday' => 'Dia di Himno y Bandera',
    '04-27'                                                                 => 'Aña di Rey',
    '06-24'                                                                 => 'Dera Gai',
    '12-15'                                                                 => 'Dia di Reino',
    '04-30'                                                                 => 'Dia di Rincon',
    '09-06'                                                                 => 'Dia di Boneiru',
    '07-02'                                                                 => 'Dia di Himno i Bandera',
    '10-10'                                                                 => 'Pais Kòrsou',
    'new-year'                                                              => 'Aña Nobo',
    '05-01'                                                                 => 'Dia di Obrero',
    'christmas'                                                             => 'Dia Pasco di Nascimento',
    'christmas-next-day'                                                    => 'Di dos Dia Pasco di Nascimento',
    'easter-48'                                                             => 'Dialuna di Carnaval',
    'easter-2'                                                              => 'Diabierna Santo',
    'easter'                                                                => 'Dia Pasco di Resureccion',
    'easter-1'                                                              => 'Di dos Dia Pasco di Resureccion',
    'easter-39'                                                             => 'Dia di Asuncion',
];
