<?php

return [
    'unification-day'               => 'Ziua Unirii',
    '03-08'                         => 'Ziua Mamei',
    'children-s-day'                => 'Ziua Copilului',
    'flag-day'                      => 'Ziua drapelului national',
    'national-anthem-day'           => 'Ziua Imnului național',
    'st-andrew-s-day'               => 'Sfântul Andrei',
    'national-holiday'              => 'Ziua națională, Ziua Marii Uniri',
    'julian-12-25-p2d'              => 'Craciun pe Rit Vechi',
    'orthodox-8'                    => 'Paştele Blăjinilor',
    '05-09'                         => 'Ziua Victoriei',
    '08-31'                         => 'Limba noastră',
    'first-saturday-of-october-p2d' => 'Ziua vinului',
    'christmas'                     => 'Craciun pe stil Nou',
    '11-21'                         => 'Ziua Cahul',
    '10-14'                         => 'Ziua capitalului',
    '01-24'                         => 'Ziua Unirii',
    '06-01'                         => 'Ziua Copilului',
    '06-26'                         => 'Ziua drapelului national',
    '07-29'                         => 'Ziua Imnului național',
    '11-30'                         => 'Sfântul Andrei',
    '12-01'                         => 'Ziua națională, Ziua Marii Uniri',
    'new-year'                      => 'Anul nou',
    '05-01'                         => 'Ziua muncii',
    '08-15'                         => 'Adormirea Maicii Domnului',
    'christmas-next-day'            => 'Două zi de Crăciun',
    'easter-2'                      => 'Vinerea Mare',
    'easter'                        => 'Paștele',
    'easter-1'                      => 'Două zi de Pasti',
    'easter-39'                     => 'Ziua Eroilor',
    'easter-49'                     => 'Rusaliile',
    'easter-50'                     => 'Două zi de Rusalii',
    'julian-12-25'                  => 'Craciun pe Rit Vechi',
    'constitution-day'              => 'Ziua Constituției',
    'independence-day'              => 'Ziua Independentei',
    'mothers-day'                   => 'Ziua Mamei',
    '1st-saturday-in-october-p2d'   => 'Ziua vinului',
];
