<?php

return array(
    'armistice-1918'     => 'Premirje 1918',
    'ascension'          => 'Vzpon',
    'assumption'         => 'Marijino vnebovzetje',
    'boxing'             => 'Boksarski dan',
    'boyne'              => 'Bitka pri Boynu',
    'christmas'          => 'Božič',
    'christmas-next-day' => 'Božič naslednji dan',
    'early-may'          => 'Zgodnji majski dopust',
    'easter'             => 'Velika noč',
    'easter-monday'      => 'Velikonočni ponedeljek',
    'epiphany'           => 'Razodetje',
    'good-friday'        => 'Dober petek',
    'independence-day'   => 'Dan samostojnosti in enotnosti',
    'labor-day'          => 'Dan dela',
    'liberation-day'     => 'Dan osvoboditve',
    'memorial-day'       => 'Dan spomina na mrtve',
    'mlk-day'            => 'Martin Luther King mlajši dan',
    'national-day'       => 'Dan državnosti',
    'new-year'           => 'Novo leto',
    'new-year-next-day'  => 'Novo leto naslednji dan',
    'pentecost'          => 'Binkoštna nedelja',
    'pentecost-monday'   => 'Binkoštna ponedeljek',
    'preseren-day'       => 'Prešernov dan',
    'rebellion-day'      => 'Dan upora proti okupatorju',
    'reformation-day'    => 'Dan reformacije',
    'royal-day'          => 'Kraljevi dan',
    'second-jan'         => 'Novo leto naslednji dan',
    'spring'             => 'Pomladni dopust',
    'st-andrews'         => 'St Andrew',
    'st-patricks'        => 'St Patrick',
    'summer'             => 'Summer Bank Holiday',
    'thanksgiving'       => 'Dan zahvalnosti',
    'toussaint'          => 'Toussaint',
    'vacation-day'       => 'Praznik dela',
    'vacation-next-day'  => 'Praznik dela naslednji dan',
    'victory-1945'       => 'Zmaga 1945',
);
