<?php

return array(
    'new-year-holiday'                     => 'Festa e Vitit të Ri',
    'league-of-lezhyo-day'                 => 'Dita e Besëlidhjes së Lezhës',
    'teacher-s-day'                        => 'Dita e Mësuesit',
    'summer-day'                           => 'Dita e Verës',
    'sultan-nevruz-s-day'                  => 'Dita e Sulltan Nevruzit',
    'catholic-easter'                      => 'Pashkët Katolike',
    'orthodox-easter'                      => 'Pashkët Ortodokse',
    'children-s-day'                       => 'Dita Ndërkombëtare e Fëmijëve',
    'mother-teresa-day'                    => 'Dita e Nënë Terezës',
    'alphabet-day'                         => 'Dita e Alfabetit',
    'youth-day'                            => 'Dita Kombëtare e Rinisë',
    'europe-day'                           => 'Dita e Evropës',
    '01-02-and-if-sunday-then-next-monday' => 'Festa e Vitit të Ri',
    '03-02'                                => 'Dita e Besëlidhjes së Lezhës',
    '03-07'                                => 'Dita e Mësuesit',
    '03-14-and-if-sunday-then-next-monday' => 'Dita e Verës',
    '03-22-and-if-sunday-then-next-monday' => 'Dita e Sulltan Nevruzit',
    'easter'                               => 'Pashkët Katolike',
    'easter-1'                             => 'Pashkët Katolike',
    'orthodox'                             => 'Pashkët Ortodokse',
    'orthodox-1'                           => 'Pashkët Ortodokse',
    '06-01'                                => 'Dita Ndërkombëtare e Fëmijëve',
    '10-19-and-if-sunday-then-next-monday' => 'Dita e Nënë Terezës',
    '11-22'                                => 'Dita e Alfabetit',
    '12-08-and-if-sunday-then-next-monday' => 'Dita Kombëtare e Rinisë',
    '05-09'                                => 'Dita e Evropës',
);