<?php

return array(
    'demilitarization-day'           => 'Ålands demilitariseringsdag',
    'autonomy-day'                   => 'Självstyrelsedagen',
    'midsummer-eve'                  => 'Midsommarafton',
    'midsummer-day'                  => 'Midsommardagen',
    'national-day'                   => 'Sveriges nationaldag',
    'saturday-after-06-20'           => 'Midsommar',
    'saturday-after-10-31'           => 'Alla Helgons dag',
    '01-13'                          => 'Knut',
    'sunday-of-march'                => 'Vasaloppet',
    '03-25'                          => 'Marie Bebådelsedag',
    'walpurgis-night'                => 'Valborgsmässoafton',
    '11-06'                          => 'Gustav-Adolf-dagen',
    '11-11'                          => 'Mårtensgås',
    '12-10'                          => 'Nobeldagen',
    '12-13'                          => 'Luciadagen',
    '03-30'                          => 'Ålands demilitariseringsdag',
    '06-09'                          => 'Självstyrelsedagen',
    'third-friday-after-06-01-12:00' => 'Midsommarafton',
    'third-saturday-after-06-01'     => 'Midsommardagen',
    'friday-after-06-19'             => 'Midsommarafton',
    '06-06'                          => 'Sveriges nationaldag',
    '04-30'                          => 'Valborgsmässoafton',
    'new-year'                       => 'Nyårsdagen',
    '01-06'                          => 'Trettondedag jul',
    '05-01'                          => 'Första Maj',
    '11-01'                          => 'Alla helgons dag',
    '12-24'                          => 'Julafton',
    'christmas'                      => 'Juldagen',
    'christmas-next-day'             => 'Annandag jul',
    '12-31'                          => 'Nyårsafton',
    'easter-2'                       => 'Långfredagen',
    'easter'                         => 'Påsk',
    'easter-1'                       => 'Annandag påsk',
    'easter-39'                      => 'Kristi himmelfärds dag',
    'easter-49'                      => 'Pingst',
    'independence-day'               => 'Självständighetsdagen',
    'mothers-day'                    => 'Mors dag',
    '3rd-friday-after-06-01-12:00'   => 'Midsommarafton',
    '3rd-saturday-after-06-01'       => 'Midsommardagen',
    'sunday-in-march'                => 'Vasaloppet',
);
