<?php

return array(
    'youth-day'              => '青年节',
    'children-s-day'         => '六一儿童节',
    'army-day'               => '建军节',
    'national-day'           => '国庆节',
    'spring-festival'        => '春节',
    'qingming-festival'      => '清明节 清明節',
    'dragon-boat-festival'   => '端午节',
    'mid-autumn-festival'    => '中秋节',
    'chinese-new-year'       => '春节',
    '05-04-12:00'            => '青年节',
    '06-01'                  => '六一儿童节',
    '08-01-12:00'            => '建军节',
    '10-01'                  => '国庆节',
    'spring-festival'        => '春节',
    'chinese-01-0-01'        => '春节',
    'chinese-5-01-solarterm' => '清明节 清明節',
    'chinese-05-0-05'        => '端午节',
    'chinese-08-0-15'        => '中秋节',
    'chinese-01-0-01-p2d'    => '春节',
    'new-year'               => '元旦',
    '03-08'                  => '国际妇女节',
    '05-01'                  => '劳动节',
);
